# Generated by Django 3.2.8 on 2022-11-22 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_current_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 8, 23, 372162))),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
