# Generated by Django 3.2.8 on 2022-11-22 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_current_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 29, 51, 286599))),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
