# Generated by Django 3.2.8 on 2022-11-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221122_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 1, 19, 29, 775690)),
        ),
    ]
