# Generated by Django 3.2.8 on 2022-11-22 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productpricehistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 4, 7, 55, 588330)),
        ),
    ]
