# Generated by Django 3.2.8 on 2022-11-22 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productpricehistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 8, 41, 52, 362330)),
        ),
    ]
