# Generated by Django 3.2.8 on 2022-11-23 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productpricehistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 23, 44, 276679)),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 23, 44, 277678)),
        ),
    ]
