# Generated by Django 3.2.8 on 2022-11-22 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_auto_20221122_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 42, 37, 611393)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 42, 37, 616258)),
        ),
    ]
