# Generated by Django 3.2.8 on 2022-11-22 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_auto_20221122_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 8, 23, 388772)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 8, 23, 395593)),
        ),
    ]
