# Generated by Django 3.2.8 on 2022-11-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0004_auto_20221122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 29, 51, 304046)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 29, 51, 308928)),
        ),
    ]
