# Generated by Django 3.2.8 on 2022-11-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0005_auto_20221122_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserrelation',
            name='listViewIsTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 1, 19, 29, 784682)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 1, 19, 29, 785683)),
        ),
    ]
