# Generated by Django 3.2.8 on 2022-11-22 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0006_auto_20221123_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuserrelation',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 4, 7, 55, 602322)),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 4, 7, 55, 603320)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
