# Generated by Django 3.2.8 on 2022-11-22 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0007_auto_20221123_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuserrelation',
            options={},
        ),
        migrations.AddField(
            model_name='productuserrelation',
            name='productIsSell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 7, 31, 35, 711003)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 7, 31, 35, 712003)),
        ),
    ]
