# Generated by Django 3.2.8 on 2022-11-23 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0009_auto_20221123_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserrelation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 9, 24, 3, 824828)),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 9, 24, 3, 735986)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 9, 24, 3, 738914)),
        ),
    ]
