# Generated by Django 3.2.8 on 2022-11-23 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0011_auto_20221123_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 23, 44, 280676)),
        ),
        migrations.AlterField(
            model_name='productuserrelation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 23, 44, 281675)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 23, 44, 280676)),
        ),
    ]
